#################################################################################
#
#                   __ _                       _   _
#   ___ ___  _ __  / _(_) __ _ _   _ _ __ __ _| |_(_) ___  _ __
#  / __/ _ \| '_ \| |_| |/ _` | | | | '__/ _` | __| |/ _ \| '_ \
# | (_| (_) | | | |  _| | (_| | |_| | | | (_| | |_| | (_) | | | |
#  \___\___/|_| |_|_| |_|\__, |\__,_|_|  \__,_|\__|_|\___/|_| |_|
#                        |___/
#
#################################################################################
# NOTE: I am working towards a minimalised configuration
# Ultimately, I want to have a once line file that calls all the
# other YAML includes
#################################################################################

homeassistant:
  # Load packages
  packages: !include_dir_named includes

  ## Customization
  ## https://www.home-assistant.io/docs/configuration/customizing-devices/#manual-customization
  # For some reason, this won't load from homeassistant.yaml. Needs to be in configuration.yaml
  customize: !include entities/customize.yaml
