#################################################################################
#
#    _            _
#   | |_ ___   __| |
#   | __/ _ \ / _` |
#   | || (_) | (_| |
#    \__\___/ \__,_|
#
#
#################################################################################
# Times of the Day
#################################################################################

- platform: tod
  name: Night
  after: sunset
  before: sunrise

- platform: tod
  name: Day
  after: sunrise
  before: sunset
