#################################################################################
#
#                       _       _
#   __      _____  _ __| | ____| | __ _ _   _
#   \ \ /\ / / _ \| '__| |/ / _` |/ _` | | | |
#    \ V  V / (_) | |  |   < (_| | (_| | |_| |
#     \_/\_/ \___/|_|  |_|\_\__,_|\__,_|\__, |
#                                       |___/
#
#################################################################################
# Workday Sensor
#################################################################################

- platform: workday
  country: AU
  province: NSW
  workdays: [mon, tue, wed, thu, fri]
  excludes: [sat, sun]
