#################################################################################
# Workday Sensor
#################################################################################
- platform: workday
  country: AU
  province: NSW
  workdays: [mon, tue, wed, thu, fri]
  excludes: [sat, sun]
