#################################################################################
#
#            _                _
#   ___ __ _| | ___ _ __   __| | __ _ _ __
#  / __/ _` | |/ _ \ '_ \ / _` |/ _` | '__|
# | (_| (_| | |  __/ | | | (_| | (_| | |
#  \___\__,_|_|\___|_| |_|\__,_|\__,_|_|
#
#
#################################################################################
# Configuration entry for nextcloud, calendars will be found automatically
# https://www.home-assistant.io/integrations/caldav
#################################################################################

- platform: caldav
  username: !secret caldav_user
  password: !secret caldav_password
  url: !secret caldav_url
  days: 60
