#################################################################################
#
#  _     _
# | |__ (_)_ __   __ _ _ __ _   _     ___  ___ _ __  ___  ___  _ __
# | '_ \| | '_ \ / _` | '__| | | |   / __|/ _ \ '_ \/ __|/ _ \| '__/
# | |_) | | | | | (_| | |  | |_| |   \__ \  __/ | | \__ \ (_) | |
# |_.__/|_|_| |_|\__,_|_|   \__, |___|___/\___|_| |_|___/\___/|_|
#                           |___/_____|
#
#################################################################################
# Binary Sensor
# https://www.home-assistant.io/integrations/binary_sensor
#################################################################################
# This is my OLD binary_sensor.yaml
# I have now adopted @frenck's configuration minimisation model
# The binary sensors are split into files by entity type
# This is retained for posterity and just in case disaster strikes
#################################################################################

#################################################################################
# Times of the Day
#################################################################################
- platform: tod
  name: Night
  after: sunset
  before: sunrise

- platform: tod
  name: Day
  after: sunrise
  before: sunset

#################################################################################
# Workday Sensor
#################################################################################
- platform: workday
  country: AU
  province: NSW
  workdays: [mon, tue, wed, thu, fri]
  excludes: [sat, sun]

#################################################################################
# Zigbee Controller online
#################################################################################
- platform: command_line
  name: Zigbee Controller
  command: "test -e /dev/ttyACM0 && echo 'Exists' || echo 'Missing'"
  payload_on: "Exists"
  payload_off: "Missing"
  scan_interval: 60
  device_class: connectivity

#################################################################################
# Ping
#################################################################################
- platform: ping
  host: !secret usg_router
  name: USG Router
  count: 3
  scan_interval: 30

- platform: ping
  host: !secret upstairs_switch
  name: Upstairs Switch
  count: 3
  scan_interval: 30

- platform: ping
  host: !secret upstairs_ap
  name: Upstairs Access Point
  count: 3
  scan_interval: 30

- platform: ping
  host: !secret cloud_key
  name: Cloud Key
  count: 3
  scan_interval: 30

- platform: ping
  host: !secret downstairs_switch
  name: Downstairs Switch
  count: 3
  scan_interval: 30

- platform: ping
  host: !secret downstairs_ap
  name: Downstairs Access Point
  count: 3
  scan_interval: 30

- platform: ping
  host: !secret rpi_switch
  name: RPi Switch
  count: 3
  scan_interval: 30

- platform: ping
  host: !secret courtyard_camera
  name: Courtyard Camera
  count: 3
  scan_interval: 30

- platform: ping
  host: !secret living_room_camera
  name: Living Room Camera
  count: 3
  scan_interval: 30
