#################################################################################
# Alarm Control Panel
# https://www.home-assistant.io/integrations/alarm_control_panel/
# https://www.home-assistant.io/integrations/manual
#################################################################################

- platform: manual
  name: Home Alarm
  code: !secret alarm_code
  code_arm_required: false
  arming_time: 0
  delay_time: 20
  trigger_time: 1
  disarmed:
    trigger_time: 0
  armed_night:
    delay_time: 0
  armed_away:
    arming_time: 0
    delay_time: 0
