#################################################################################
#
#                _                        _   _
#     __ _ _   _| |_ ___  _ __ ___   __ _| |_(_) ___  _ __
#    / _` | | | | __/ _ \| '_ ` _ \ / _` | __| |/ _ \| '_ \
#   | (_| | |_| | || (_) | | | | | | (_| | |_| | (_) | | | |
#    \__,_|\__,_|\__\___/|_| |_| |_|\__,_|\__|_|\___/|_| |_|
#
#
#################################################################################
# This handles the loading of my automations
# https://www.home-assistant.io/docs/automation/
#################################################################################

# Automations I create in the UI
automation ui: !include ../automations.yaml

# My own handmade automations
automation manual: !include_dir_list ../automations
# automation manual: !include_dir_merge_list automations/
