#################################################################################
#
#  _     _
# | |__ (_)_ __   __ _ _ __ _   _     ___  ___ _ __  ___  ___  _ __ ___
# | '_ \| | '_ \ / _` | '__| | | |   / __|/ _ \ '_ \/ __|/ _ \| '__/ __|
# | |_) | | | | | (_| | |  | |_| |   \__ \  __/ | | \__ \ (_) | |  \__ \
# |_.__/|_|_| |_|\__,_|_|   \__, |___|___/\___|_| |_|___/\___/|_|  |___/
#                           |___/_____|
#
#################################################################################
# Binary Sensors
# https://www.home-assistant.io/integrations/binary_sensor
#################################################################################

#################################################################################
# Times of the Day
#################################################################################
- platform: tod
  name: Night
  after: sunset
  before: sunrise

- platform: tod
  name: Day
  after: sunrise
  before: sunset

#################################################################################
# Workday Sensor
#################################################################################
- platform: workday
  country: AU
  province: NSW
  workdays: [mon, tue, wed, thu, fri]
  excludes: [sat, sun]

#################################################################################
# Zigbee Controller online
#################################################################################
- platform: command_line
  name: Zigbee Controller
  command: "test -e /dev/ttyACM0 && echo 'Exists' || echo 'Missing'"
  payload_on: "Exists"
  payload_off: "Missing"
  scan_interval: 60
  device_class: connectivity

#################################################################################
# Ping
#################################################################################
- platform: ping
  host: 192.168.4.1
  name: USG Router
  count: 3
  scan_interval: 30

- platform: ping
  host: 192.168.4.2
  name: Upstairs Switch
  count: 3
  scan_interval: 30

- platform: ping
  host: 192.168.4.3
  name: Upstairs Access Point
  count: 3
  scan_interval: 30

- platform: ping
  host: 192.168.4.4
  name: Cloud Key
  count: 3
  scan_interval: 30

- platform: ping
  host: 192.168.4.5
  name: Downstairs Switch
  count: 3
  scan_interval: 30

- platform: ping
  host: 192.168.4.6
  name: Downstairs Access Point
  count: 3
  scan_interval: 30

- platform: ping
  host: 192.168.4.7
  name: RPi Switch
  count: 3
  scan_interval: 30

- platform: ping
  host: 192.168.4.26
  name: Courtyard Camera
  count: 3
  scan_interval: 30

- platform: ping
  host: 192.168.4.27
  name: Living Room Camera
  count: 3
  scan_interval: 30
