#################################################################################
#
#  _     _
# | |__ (_)_ __   __ _ _ __ _   _     ___  ___ _ __  ___  ___  _ __
# | '_ \| | '_ \ / _` | '__| | | |   / __|/ _ \ '_ \/ __|/ _ \| '__/
# | |_) | | | | | (_| | |  | |_| |   \__ \  __/ | | \__ \ (_) | |
# |_.__/|_|_| |_|\__,_|_|   \__, |___|___/\___|_| |_|___/\___/|_|
#                           |___/_____|
#
#################################################################################
# Binary Sensor
# https://www.home-assistant.io/integrations/binary_sensor
#################################################################################

# binary_sensor: !include ../entities/binary_sensor.yaml
binary_sensor: !include_dir_merge_list ../entities/binary_sensor
