#################################################################################
#
#       _ _                 _
#   ___| (_)_ __ ___   __ _| |_ ___
#  / __| | | '_ ` _ \ / _` | __/ _ \
# | (__| | | | | | | | (_| | ||  __/
#  \___|_|_|_| |_| |_|\__,_|\__\___|
#
#
#################################################################################
# Generic Thermostat
# https://www.home-assistant.io/integrations/generic_thermostat/
#################################################################################

- platform: generic_thermostat
  unique_id: bedroom_heater_controller
  name: Bedroom Heater Controller
  heater: switch.plug_2_on_off
  target_sensor: sensor.bedroom_temperature
  min_temp: 5
  max_temp: 30
  target_temp: 16
  cold_tolerance: 0.2
  hot_tolerance: 0.3
  precision: 0.1
  min_cycle_duration:
    seconds: 5
  initial_hvac_mode: "off"
  away_temp: 5
  home_temp: 17
  # UNUSED: Preset modes
  #sleep_temp: 5
  #comfort_temp: 18
  #activity_temp: 18.5

- platform: generic_thermostat
  unique_id: living_room_heater_controller
  name: Living Room Heater Controller
  heater: switch.plug_3_on_off
  target_sensor: sensor.living_room_motion_temperature
  min_temp: 5
  max_temp: 30
  target_temp: 16
  cold_tolerance: 0.2
  hot_tolerance: 0.3
  precision: 0.1
  min_cycle_duration:
    seconds: 5
  initial_hvac_mode: "off"
  away_temp: 5
  home_temp: 15
  # UNUSED: Preset modes
  #sleep_temp: 5
  #comfort_temp: 18
  #activity_temp: 18.5

- platform: generic_thermostat
  unique_id: computer_fan_controller
  name: Computer Fan Controller
  heater: switch.plug_5_on_off
  target_sensor: sensor.average_rpi_temperature
  min_temp: 25
  max_temp: 90
  target_temp: 50
  ac_mode: true
  cold_tolerance: 5
  hot_tolerance: 5
  precision: 0.1
  min_cycle_duration:
    seconds: 30
  initial_hvac_mode: "cool"
  away_temp: 5
  home_temp: 50
