#################################################################################
#
#      _            _             _                  _
#   __| | _____   _(_) ___ ___   | |_ _ __ __ _  ___| | _____ _ __ ___
#  / _` |/ _ \ \ / / |/ __/ _ \  | __| '__/ _` |/ __| |/ / _ \ '__/ __|
# | (_| |  __/\ V /| | (_|  __/  | |_| | | (_| | (__|   <  __/ |  \__ \
#  \__,_|\___| \_/ |_|\___\___|___\__|_|  \__,_|\___|_|\_\___|_|  |___/
#                            |_____|
#
#################################################################################
# Device Tracker
# https://www.home-assistant.io/integrations/device_tracker
#################################################################################

#################################################################################
# Bluetooth Integration
# This tracker discovers new devices on boot and tracks Bluetooth devices
# https://www.home-assistant.io/integrations/bluetooth_tracker/
# DISABLED: Was tracking too many of the neighbours devices
#################################################################################
- platform: bluetooth_tracker
