#################################################################################
#
#  _                                        _     _              _
# | |__   ___  _ __ ___   ___  __ _ ___ ___(_)___| |_ __ _ _ __ | |_
# | '_ \ / _ \| '_ ` _ \ / _ \/ _` / __/ __| / __| __/ _` | '_ \| __|
# | | | | (_) | | | | | |  __/ (_| \__ \__ \ \__ \ || (_| | | | | |_
# |_| |_|\___/|_| |_| |_|\___|\__,_|___/___/_|___/\__\__,_|_| |_|\__|
#
#
#################################################################################
# The Home Assistant integration provides generic implementations
# https://www.home-assistant.io/integrations/homeassistant/
#################################################################################

homeassistant:
  ## Customization
  ## https://www.home-assistant.io/docs/configuration/customizing-devices/#manual-customization
  # For some reason this doesn't load. Needs to be in configuration.yaml
  # customize: !include ../entities/customize.yaml

  ## External Directories
  ## List of external URLs that can be fetched
  ## https://www.home-assistant.io/docs/configuration/basic/#allowlist_external_urls
  allowlist_external_dirs:
    - /  # Home Assistant root
    - /tmp  # Home Assistant snapshots
  media_dirs:
    local: /media
