#################################################################################
#
#
#    ___  ___ _ __  ___  ___  _ __
#   / __|/ _ \ '_ \/ __|/ _ \| '__|
#   \__ \  __/ | | \__ \ (_) | |
#   |___/\___|_| |_|___/\___/|_|
#
#
#################################################################################

sensor: !include ../entities/sensor.yaml
