# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Default
title: "Matho's Home Assistant Blog"
email: support@marathonsoftware.com.au
description: >-  # this means to ignore newlines until "baseurl:"
  Blogging about my Home Assistant and GitHub experiences.
baseurl: ""  # the subpath of your site, e.g. /blog
url: "https://nzrunner.github.io/home-assistant"  # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nzrunner
github_username: nzrunner
quote: "Consumer and now contributor of the open-source community."

# Author details
authors:
  mark:
    name: Mark Matheson
    display_name: Matho
    avatar: "/assets/images/mark-circle-200x200.png"
    gravatar: 8db5ca9bd8374ed0efbab82888bc1e5c
    email: support@marathonsoftware.com.au
    web: https://marathonsoftware.com.au
    twitter: https://twitter.com/nzrunner
    github: https://github.com/nzrunner
    description: "Consumer and now contributor of the open-source community."

# Specific to Hamilton theme
location: "Sydney, Australia"
skin: midnight
date_format: "%-d %b %Y"
author: "Mark Matheson"
disqus: github-blog
avatar: /assets/images/mark-circle-200x200.png
subscribe: true
paginate: 5

# Jekyll SEO tag
logo: /assets/images/mark-matheson-digital-business-consultant.png
defaults:
  - scope:
      path: ""
    values:
      image: "/assets/images/mark-matheson-digital-business-consultant.png"
tagline: Blogging about my Home Assistant and GitHub experiences.
twitter:
  username: nzrunner
  card: summary_large_image
facebook:
  app_id: 275904333606308
social:
  name: Mark Matheson
  links:
    - https://www.twitter.com/nzrunner
    - https://www.facebook.com/nzrunner
    - https://www.linkedin.com/in/nzrunner
    - https://github.com/nzrunner

# Build settings
# theme: minima
remote_theme: ngzhio/jekyll-theme-hamilton
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin
  - jekyll-mentions
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Jekyll Admin
jekyll_admin:
  homepage: "posts"
  hidden_links:
  # - posts
  # - pages
  # - staticfiles
  # - datafiles
  # - configuration
