# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Matho's Home Assistant Blog"
email: support@marathonsoftware.com.au
description: >-  # this means to ignore newlines until "baseurl:"
  A Home Assistant and GitHub blog about my experiences with these products.
baseurl: "/home-assistant"  # the subpath of your site, e.g. /blog
url: "https://nzrunner.github.io"  # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nzrunner
github_username: nzrunner

# Specific to Hamilton theme
location: "Sydney, Australia"
skin: midnight
date_format: "%-d %b %Y"
author: "Mark Matheson"
disqus: github-blog
avatar: /assets/images/mark-circle-200x200.png
subscribe: false
paginate: 5

# Jekyll SEO tag
logo: /assets/images/mark-matheson-digital-business-consultant.png
defaults:
  - scope:
      path: ""
    values:
      image: "{{ site.url }}/{{ site.baseurl }}/assets/images/mark-matheson-digital-business-consultant.png"
tagline: Home Assistant and GitHub blog
twitter:
  username: nzrunner
  card: summary_large_image
facebook:
  app_id: 275904333606308
social:
  name: Mark Matheson
  links:
    - https://www.twitter.com/nzrunner
    - https://www.facebook.com/nzrunner
    - https://www.linkedin.com/in/nzrunner
    - https://github.com/nzrunner

# Build settings
# theme: minima
remote_theme: ngzhio/jekyll-theme-hamilton
plugins:
  # Don;t want RSS feed
  # - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-remote-theme  # add this line to the plugins list if you already have one

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
