#################################################################################
#
#    _              _                               _                _
#   | |__   ___  __| |_ __ ___   ___  _ __ ___     | |__   ___  __ _| |_ ___ _ __
#   | '_ \ / _ \/ _` | '__/ _ \ / _ \| '_ ` _ \    | '_ \ / _ \/ _` | __/ _ \ '__|
#   | |_) |  __/ (_| | | | (_) | (_) | | | | | |   | | | |  __/ (_| | ||  __/ |
#   |_.__/ \___|\__,_|_|  \___/ \___/|_| |_| |_|___|_| |_|\___|\__,_|\__\___|_|
#                                             |_____|
#
#################################################################################
# Generic Thermostat
# https://www.home-assistant.io/integrations/generic_thermostat/
#################################################################################

- platform: generic_thermostat
  unique_id: 94991c44-d4ee-11ed-afa1-0242ac120002
  name: Bedroom Heater Controller
  heater: switch.plug_2_on_off
  target_sensor: sensor.bedroom_temperature
  min_temp: 5
  max_temp: 30
  target_temp: 16
  cold_tolerance: 0.2
  hot_tolerance: 0.3
  precision: 0.1
  min_cycle_duration:
    seconds: 5
  initial_hvac_mode: "off"
  away_temp: 5
  home_temp: 17
  # UNUSED: Preset modes
  # sleep_temp: 5
  # comfort_temp: 18
  # activity_temp: 18.5
