#################################################################################
# Generic Thermostat
# https://www.home-assistant.io/integrations/generic_thermostat/
#################################################################################

- platform: generic_thermostat
  unique_id: living_room_heater_controller
  name: Living Room Heater Controller
  heater: switch.plug_3_on_off
  target_sensor: sensor.living_room_motion_temperature
  min_temp: 5
  max_temp: 30
  target_temp: 16
  cold_tolerance: 0.2
  hot_tolerance: 0.3
  precision: 0.1
  min_cycle_duration:
    seconds: 5
  initial_hvac_mode: "off"
  away_temp: 5
  home_temp: 15
  # UNUSED: Preset modes
  # sleep_temp: 5
  # comfort_temp: 18
  # activity_temp: 18.5
