name: "Keep workflows alive"
# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: 0 0 * * 0

jobs:
  keepalive:
    name: Keep workflows alive
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Keep alive
        uses: gautamkrishnar/keepalive-workflow@master
        with:
          committer_username: nzrunner
          committer_email: nzrunner@users.noreply.github.com
