# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '29 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 
          This issue has been identified as stale because it has gone 60 days with no activity.

          The issue will be closed in 5 days. If this is incorrect, simply comment on the issue, or remove the stale label.
        stale-pr-message:
          This PR has been identified as stale because it has gone 60 days with no activity.

          The PR will be closed in 5 days. If this is incorrect, simply comment on the issue, or remove the stale label.
        close-issue-message:
          This issue was closed because it has been stalled for 65 days with no activity.
        close-pr-message:
          This PR was closed because it has been stalled for 65 days with no activity.
        days-before-stale: 60
        days-before-close: 5
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        exempt-issue-assignees: 'nzrunner'
        exempt-pr-assignees: 'nzrunner'
        exempt-issue-labels: 'keep-me'
        exempt-pr-labels: 'keep-me'
